import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript

// Get the base URL from the current window location
const getBaseUrl = () => {
  const { protocol, hostname, port } = window.location;
  return `${protocol}//${hostname}${port ? `:${port}` : ""}`;
};

export const api = createClient(
  createFetchClient<paths>({
    baseUrl: getBaseUrl(),
  })
);
