// AUTO-GENERATED by scripts/generate-static-assets.mjs -- do not edit by hand.
// Regenerated on every `npm run build` from the built `dist/` output.
//
// This placeholder ships committed so `npx convex dev` has something to
// import before the first `npm run build` has run.

export interface StaticAsset {
  contentType: string;
  base64: string;
}

export const staticAssets: Record<string, StaticAsset> = {};
